name: CI for JavaScript Algorithms

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Vérifie le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Installe Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Installe les dépendances
      - name: Install dependencies
        run: npm install

      # Lance les tests
      - name: Run tests
        run: npm test
